// tech name -> { slug: simpleicons slug, color: brand hex (without #) }
const badges: Record<string, { slug: string; color: string }> = {
  // Frontend
  "react": { slug: "react", color: "61DAFB" },
  "next.js": { slug: "nextdotjs", color: "000000" },
  "nextjs": { slug: "nextdotjs", color: "000000" },
  "vue.js": { slug: "vuedotjs", color: "4FC08D" },
  "vuejs": { slug: "vuedotjs", color: "4FC08D" },
  "vue": { slug: "vuedotjs", color: "4FC08D" },
  "angular": { slug: "angular", color: "0F0F11" },
  "svelte": { slug: "svelte", color: "FF3E00" },
  "typescript": { slug: "typescript", color: "3178C6" },
  "javascript": { slug: "javascript", color: "F7DF1E" },
  "html": { slug: "html5", color: "E34F26" },
  "html5": { slug: "html5", color: "E34F26" },
  "css": { slug: "css3", color: "1572B6" },
  "css3": { slug: "css3", color: "1572B6" },
  "sass": { slug: "sass", color: "CC6699" },
  "scss": { slug: "sass", color: "CC6699" },
  "tailwind css": { slug: "tailwindcss", color: "06B6D4" },
  "tailwindcss": { slug: "tailwindcss", color: "06B6D4" },
  "bootstrap": { slug: "bootstrap", color: "7952B3" },
  "redux": { slug: "redux", color: "764ABC" },
  "zustand": { slug: "zustand", color: "443E38" },
  "recoil": { slug: "recoil", color: "3578E5" },
  "react query": { slug: "reactquery", color: "FF4154" },
  "webpack": { slug: "webpack", color: "8DD6F9" },
  "vite": { slug: "vite", color: "646CFF" },
  "storybook": { slug: "storybook", color: "FF4785" },
  "mdx": { slug: "mdx", color: "1B1F24" },
  "emotion": { slug: "emotion", color: "C865B9" },
  "styled-components": { slug: "styledcomponents", color: "DB7093" },
  "mui": { slug: "mui", color: "007FFF" },
  "material-ui": { slug: "mui", color: "007FFF" },
  "framer motion": { slug: "framer", color: "0055FF" },
  "three.js": { slug: "threedotjs", color: "000000" },
  "d3": { slug: "d3dotjs", color: "F9A03C" },
  "jquery": { slug: "jquery", color: "0769AD" },
  "gatsby": { slug: "gatsby", color: "663399" },
  "remix": { slug: "remix", color: "000000" },
  "astro": { slug: "astro", color: "BC52EE" },
  "reanimated": { slug: "react", color: "61DAFB" },

  // Backend
  "node.js": { slug: "nodedotjs", color: "5FA04E" },
  "nodejs": { slug: "nodedotjs", color: "5FA04E" },
  "express": { slug: "express", color: "000000" },
  "nestjs": { slug: "nestjs", color: "E0234E" },
  "spring boot": { slug: "springboot", color: "6DB33F" },
  "spring": { slug: "spring", color: "6DB33F" },
  "spring security": { slug: "springsecurity", color: "6DB33F" },
  "django": { slug: "django", color: "092E20" },
  "flask": { slug: "flask", color: "000000" },
  "fastapi": { slug: "fastapi", color: "009688" },
  "ruby on rails": { slug: "rubyonrails", color: "D30001" },
  "rails": { slug: "rubyonrails", color: "D30001" },
  "laravel": { slug: "laravel", color: "FF2D20" },
  "php": { slug: "php", color: "777BB4" },
  "go": { slug: "go", color: "00ADD8" },
  "golang": { slug: "go", color: "00ADD8" },
  "rust": { slug: "rust", color: "000000" },
  "java": { slug: "java", color: "437291" },
  "kotlin": { slug: "kotlin", color: "7F52FF" },
  "python": { slug: "python", color: "3776AB" },
  "c#": { slug: "csharp", color: "512BD4" },
  ".net": { slug: "dotnet", color: "512BD4" },
  "graphql": { slug: "graphql", color: "E10098" },
  "grpc": { slug: "grpc", color: "244C5A" },
  "socket.io": { slug: "socketdotio", color: "010101" },
  "jpa": { slug: "hibernate", color: "59666C" },
  "swagger": { slug: "swagger", color: "85EA2D" },
  "nextauth.js": { slug: "nextdotjs", color: "000000" },
  "next.js api routes": { slug: "nextdotjs", color: "000000" },
  "celery": { slug: "celery", color: "37814A" },

  // Database
  "postgresql": { slug: "postgresql", color: "4169E1" },
  "mysql": { slug: "mysql", color: "4479A1" },
  "mongodb": { slug: "mongodb", color: "47A248" },
  "redis": { slug: "redis", color: "FF4438" },
  "sqlite": { slug: "sqlite", color: "003B57" },
  "mariadb": { slug: "mariadb", color: "003545" },
  "firebase": { slug: "firebase", color: "DD2C00" },
  "firebase firestore": { slug: "firebase", color: "DD2C00" },
  "supabase": { slug: "supabase", color: "3FCF8E" },
  "prisma": { slug: "prisma", color: "2D3748" },
  "typeorm": { slug: "typeorm", color: "FE0803" },
  "sequelize": { slug: "sequelize", color: "52B0E7" },
  "mongoose": { slug: "mongoose", color: "880000" },
  "elasticsearch": { slug: "elasticsearch", color: "005571" },
  "dynamodb": { slug: "amazondynamodb", color: "4053D6" },
  "influxdb": { slug: "influxdb", color: "22ADF6" },

  // DevOps
  "docker": { slug: "docker", color: "2496ED" },
  "kubernetes": { slug: "kubernetes", color: "326CE5" },
  "aws": { slug: "amazonwebservices", color: "232F3E" },
  "aws ec2": { slug: "amazonec2", color: "FF9900" },
  "aws s3": { slug: "amazons3", color: "569A31" },
  "aws lambda": { slug: "awslambda", color: "FF9900" },
  "gcp": { slug: "googlecloud", color: "4285F4" },
  "azure": { slug: "microsoftazure", color: "0078D4" },
  "terraform": { slug: "terraform", color: "844FBA" },
  "github actions": { slug: "githubactions", color: "2088FF" },
  "jenkins": { slug: "jenkins", color: "D24939" },
  "nginx": { slug: "nginx", color: "009639" },
  "vercel": { slug: "vercel", color: "000000" },
  "netlify": { slug: "netlify", color: "00C7B7" },
  "heroku": { slug: "heroku", color: "430098" },
  "linux": { slug: "linux", color: "FCC624" },
  "prometheus": { slug: "prometheus", color: "E6522C" },
  "grafana": { slug: "grafana", color: "F46800" },
  "argocd": { slug: "argo", color: "EF7B4D" },
  "ci/cd": { slug: "githubactions", color: "2088FF" },

  // Mobile
  "react native": { slug: "react", color: "61DAFB" },
  "flutter": { slug: "flutter", color: "02569B" },
  "expo": { slug: "expo", color: "000020" },
  "swift": { slug: "swift", color: "F05138" },
  "android": { slug: "android", color: "34A853" },
  "ios": { slug: "ios", color: "000000" },

  // Etc
  "git": { slug: "git", color: "F05032" },
  "github": { slug: "github", color: "181717" },
  "figma": { slug: "figma", color: "F24E1E" },
  "jira": { slug: "jira", color: "0052CC" },
  "notion": { slug: "notion", color: "000000" },
  "slack": { slug: "slack", color: "4A154B" },
  "tensorflow lite": { slug: "tensorflow", color: "FF6F00" },
  "tensorflow": { slug: "tensorflow", color: "FF6F00" },
  "pytorch": { slug: "pytorch", color: "EE4C2C" },
  "mediapipe": { slug: "google", color: "4285F4" },
  "hugging face transformers": { slug: "huggingface", color: "FFD21E" },
  "konlpy": { slug: "python", color: "3776AB" },
  "beautifulsoup": { slug: "python", color: "3776AB" },
  "plotly": { slug: "plotly", color: "3F4F75" },
  "streamlit": { slug: "streamlit", color: "FF4B4B" },
  "jest": { slug: "jest", color: "C21325" },
  "cypress": { slug: "cypress", color: "69D3A7" },
  "vitest": { slug: "vitest", color: "6E9F18" },
};

// 밝은 배경색에서 글자가 안 보이는 색상 -> logoColor를 black으로
const lightColors = new Set([
  "F7DF1E", "8DD6F9", "06B6D4", "61DAFB", "4FC08D",
  "85EA2D", "FCC624", "3FCF8E", "FFD21E", "FF9900",
  "00C7B7", "69D3A7", "22ADF6", "6E9F18",
]);

export function getTechBadgeUrl(techName: string): string | null {
  const key = techName.toLowerCase().trim();
  const badge = badges[key];
  if (!badge) return null;

  const label = encodeURIComponent(techName);
  const logoColor = lightColors.has(badge.color) ? "black" : "white";

  return `https://img.shields.io/badge/${label}-${badge.color}?style=for-the-badge&logo=${badge.slug}&logoColor=${logoColor}`;
}
